Repository noiopen/io-sdk, pull requests merged in 2020-07, with the labels that each got.

#38 Implements docker image for scheduler components
  Makefile
  admin/package.json
  admin/src/Body.svelte
  admin/src/Config.svelte
  admin/src/Menu.svelte
  admin/src/Scheduler.svelte
  iosdk/config.go
  iosdk/const.go
  iosdk/main.go
  iosdk/scheduler.go
  iosdk/scheduler_test.go
  iosdk/start.go
  iosdk/start_test.go
  scheduler/Dockerfile
  scheduler/Makefile
  scheduler/README.md
  scheduler/package-lock.json
  scheduler/package.json
  scheduler/src/app.ts
  scheduler/src/command/command-line.ts
  scheduler/src/index.ts
  scheduler/src/job/command-line-cron-job.ts
Labels: docker, enhancement

#41 Feature/add button make new import
  admin/src/Import.svelte
  admin/src/ImportPreview.svelte
Labels: enhancement

#36 Added Feed in Home page
  admin/src/Home.svelte
Labels: enhancement, javascript
